"""empty message

Revision ID: 722aa598ccf3
Revises: 
Create Date: 2021-06-14 12:41:06.125054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722aa598ccf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbershops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=False),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('phoneNumber', sa.String(length=50), nullable=False),
    sa.Column('operationHours', sa.String(length=2000), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bizImage', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postalCode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatarUrl', sa.String(length=255), nullable=True),
    sa.Column('preferredHairStyle', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('barbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatarUrl', sa.String(length=255), nullable=True),
    sa.Column('barbershopId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbershopId'], ['barbershops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('barberId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barberId'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewBody', sa.String(length=2000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('barberId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barberId'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('appointments')
    op.drop_table('barbers')
    op.drop_table('users')
    op.drop_table('barbershops')
    # ### end Alembic commands ###
